version: '3.8'
services:
  test-postgres:
    image: postgres:15
    container_name: satoshi_hub_test_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: satoshi_hub_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d satoshi_hub_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:7-alpine
    container_name: satoshi_hub_test_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - test_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_postgres_data:
    driver: local
  test_redis_data:
    driver: local
