name: satoshi_hub_mobile
description: Cross-chain Testnet Hub - Flutter mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.0
  
  # HTTP client
  dio: ^5.3.0
  
  # Web3 & Wallet
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.1.0
  
  # UI & Navigation
  go_router: ^12.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # Utils
  shared_preferences: ^2.2.0
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.14
  
  # Development
  flutter_dotenv: ^5.1.0
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
