name: satoshi_hub
description: "Cross-chain bridge application"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.1.2
  web3dart: ^2.7.3
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  ethereum_addresses: ^1.0.2
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
assets:
    - .env
    - assets/images/
    - assets/tokens/
    - assets/icons/
