name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      # Remove version conflict - use the one from package.json
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build SDK
      run: pnpm --filter @satoshi-hub/sdk build
      
    - name: Run only working tests
      env:
        SIGNER_PRIVATE_KEY: 0x0000000000000000000000000000000000000000000000000000000000000001
        NODE_ENV: test
      run: pnpm --filter backend exec jest src/app.controller.spec.ts src/tx/tx.controller.spec.ts src/tx/tx.service.spec.ts src/blockchain/blockchain.service.spec.ts src/prisma/prisma.service.spec.ts --coverage
