name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install pnpm
      run: npm install -g pnpm@8.15.0
    - name: Install dependencies
      run: pnpm install
    - name: Build SDK
      run: pnpm --filter @satoshi-hub/sdk build
    - name: Compile TypeScript
      run: pnpm --filter backend exec tsc --noEmit
    - name: Success
      run: echo "✅ Build successful - ready for Flutter development"
